version: '3'
services:
  proxy:
    image: nginx
    restart: always
    container_name: nugget_proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20000:20000
  
  postgres:
    image: postgres
    restart: always
    container_name: nugget_postgres
    environment:
      POSTGRES_PASSWORD: void
      POSTGRES_USER: void
      POSTGRES_DB: void
    volumes:
        - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 19999:5432
  
  redis:
    image: redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    container_name: nugget_redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - 19998:6379

  mongo:
    image: mongo
    restart: always
    container_name: nugget_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: void
      MONGO_INITDB_ROOT_PASSWORD: void
    ports:
      - 19997:27017